#include "global.h"

// int CANVAS_WIDTH = 1920 / 8;
// int CANVAS_HEIGHT = 1080 / 8;
int CANVAS_WIDTH = 1000;
int CANVAS_HEIGHT = 1000;
int ORIGIN_X = CANVAS_WIDTH / 2;
int ORIGIN_Y = CANVAS_HEIGHT / 2;
int STROKE_SIZE = 3;
